/** Unit 2 lessons (and the review / world sections that follow it), in book order, plus their tip cards. */
import type { AulaStep } from "../aulas.ts";
import type { Lesson } from "../schema.ts";

const pav = (unit: "u02" | "pds1" | "trab1" | "mundo1", pages: number[], concept: string) => ({ sourceId: "pav1-student" as const, unit, pages, concept });
const verbIds = (slug: string) => ["eu", "tu", "ele", "nos", "eles"].map((p) => `grammar.${slug}.${p}`);
const nouns = (...s: string[]) => s.map((x) => `vocab.noun.${x}`);
const adjs = (...s: string[]) => s.map((x) => `vocab.adjective.${x}`);
const fn = (unit: string, ...s: string[]) => s.map((x) => `function.${unit}.${x}`);
const frames = (...s: string[]) => s.map((x) => `grammar.frame.${x}`);
const errs = (...s: string[]) => s.map((x) => `grammar.error.${x}`);
const nums = (...n: number[]) => n.map((x) => `vocab.number.n${x}`);

export const U02_LESSONS: Lesson[] = [
  {
    id: "u02.apresentar",
    unit: "u02",
    title: "Apresento-te a minha irmã — apresentar pessoas",
    source: pav("u02", [34, 35], "introduce-someone"),
    itemIds: [
      ...fn("u02", "apresento_te", "esta_e_colega", "muito_prazer", "bem_vinda", "ja_conheces", "que_giro"),
      ...nouns("marido", "mulher", "namorado", "namorada", "colega", "amigo", "amiga", "familia"),
      ...frames("esta_namorada", "nosso_colega", "eu_conheco"),
      ...errs("o_namorado"),
    ],
    canDo: ["cd01.introduce-self", "cd03.greet-polite", "cd05.family-describe"],
  },
  {
    id: "u02.verbos_er",
    unit: "u02",
    title: "Bebes um café? — verbos em -er",
    source: pav("u02", [34, 35, 50], "verbs-er"),
    itemIds: [
      ...verbIds("comer"),
      ...verbIds("beber"),
      ...verbIds("viver"),
      "function.u02.bebes_cafe",
      ...frames("tu_comes", "nos_vivemos", "eles_comem", "bebo_sim"),
    ],
    canDo: ["cd02.personal-info", "cd06.routines", "cd09.order-food"],
  },
  {
    id: "u02.familia",
    unit: "u02",
    title: "Esta é a minha mãe — a família",
    source: pav("u02", [36, 37, 51], "family-possessives"),
    itemIds: [
      ...nouns("pai", "mae", "filho", "filha", "irmao", "irma", "avo_m", "avo_f", "neto", "neta", "tio", "tia"),
      ...adjs("casado", "solteiro"),
      ...frames("a_minha_mae", "os_meus_avos", "carro_dele"),
      ...errs("esta_irma", "meu_pai", "pais_dela"),
    ],
    canDo: ["cd05.family-describe", "cd02.personal-info"],
  },
  {
    id: "u02.sala_aula",
    unit: "u02",
    title: "Onde está o meu livro? — a sala de aula e o verbo estar",
    source: pav("u02", [39, 40, 50], "classroom-location"),
    itemIds: [
      ...nouns("mesa", "quadro", "caderno", "borracha", "estojo"),
      ...verbIds("estar"),
      ...fn("u02", "em_cima_de", "debaixo_de", "dentro_de", "ao_lado_de"),
      ...frames("livro_esta", "dentro_do_estojo", "debaixo_da_cadeira", "o_que_e_isto"),
      ...errs("oculos_estao", "atras_da_porta"),
    ],
    canDo: ["cd13.home", "cd23.speak-short"],
  },
  {
    id: "u02.numeros",
    unit: "u02",
    title: "Trinta, cinquenta, cem — números até 199",
    source: pav("u02", [41], "numbers-to-199"),
    itemIds: [...nums(21, 22, 30, 38, 40, 50, 60, 70, 80, 90, 100, 101, 120, 150, 199), ...frames("avo_noventa", "mae_sessenta"), ...errs("cem_livros")],
    canDo: ["cd07.numbers-prices"],
  },
  {
    id: "u02.descrever",
    unit: "u02",
    title: "Ela é alta e simpática — descrever pessoas",
    source: pav("u02", [42, 45, 50], "describing-people"),
    itemIds: [
      ...adjs("alto", "baixo", "magro", "gordo", "simpatico", "antipatico", "timido", "sociavel", "trabalhador", "preguicoso", "cansado", "descansado"),
      ...fn("u02", "cabelo_curto", "usa_oculos"),
      ...frames("hoje_estou", "irmao_e_alto", "amigas_simpaticas"),
      ...errs("sou_solteira", "ana_alta"),
    ],
    canDo: ["cd05.family-describe", "cd23.speak-short"],
  },
  {
    id: "u02.passatempos",
    unit: "u02",
    title: "Gosto de dançar — passatempos, aprender e perceber",
    source: pav("u02", [35, 42], "hobbies"),
    itemIds: [
      ...fn("u02", "o_que_gostas", "gosto_ler", "gosto_pintar", "gosto_futebol", "gosto_cinema", "gosto_dancar"),
      ...verbIds("aprender"),
      ...verbIds("perceber"),
      ...frames("eu_aprendo", "voces_percebem", "gosto_de"),
    ],
    canDo: ["cd06.routines", "cd04.repair"],
  },
  {
    id: "pds1.revisao",
    unit: "pds1",
    title: "Ponto da Situação 1 — revisão das Unidades 0–2",
    source: pav("pds1", [52, 53, 54, 55, 56, 57], "review-units-0-2"),
    itemIds: [
      "grammar.ser.eles",
      "grammar.ter.tu",
      "grammar.estar.eu",
      "grammar.viver.nos",
      ...nouns("mae", "irmao"),
      ...adjs("alto", "simpatico"),
      ...nums(50, 100),
      ...fn("u02", "em_frente_de", "atras_de", "entre"),
      ...frames("falamos", "esta_sim", "quantos_anos", "uma_irma"),
      ...errs("irmaos_altos", "ana_esta_casa"),
    ],
    canDo: ["cd01.introduce-self", "cd02.personal-info", "cd05.family-describe", "cd13.home"],
  },
  {
    id: "trab1.colegas",
    unit: "trab1",
    title: "Muito gosto, Dra. Rita! — o mundo do trabalho",
    source: pav("trab1", [58, 59], "workplace-basics"),
    itemIds: [
      ...fn("trab1", "muito_gosto", "igualmente", "nova_colega", "um_momento", "o_sr_esta", "procura_se"),
      ...["contabilista", "rececionista", "diretor"].map((s) => `vocab.profession.${s}`),
      ...adjs("organizado", "desarrumado", "atento", "distraido", "paciente", "impaciente", "curioso", "comunicativo"),
      ...frames("aquele_senhor", "prazer_conhecer_te"),
    ],
    canDo: ["cd03.greet-polite", "cd01.introduce-self", "cd21.forms"],
  },
  {
    id: "mundo1.lusofonia",
    unit: "mundo1",
    title: "Onde se fala português? — os países da CPLP",
    source: pav("mundo1", [60, 61, 62], "lusophone-world"),
    itemIds: [
      ...["portugal", "brasil", "angola", "mocambique", "cabo_verde", "guine", "saotome", "timor"].map((s) => `vocab.nationality.${s}`),
      ...fn("mundo1", "onde_se_fala", "cplp", "dia_lingua", "macau"),
      "grammar.origin.cabo_verde",
      "grammar.origin.mocambique",
      ...frames("de_cabo_verde", "cabo_verdiana", "angola_portugues"),
    ],
    canDo: ["cd01.introduce-self", "cd22.listen-clear"],
  },
];

export const U02_AULAS: Record<string, AulaStep[]> = {
  "u02.apresentar": [
    { kind: "title", big: "Apresento-te a minha irmã", small: "Apresentar amigos, família e colegas", say: "Apresento-te a minha irmã.", ms: 3800 },
    {
      kind: "table",
      kicker: "APRESENTAR",
      rows: [
        ["Este é o Hadi.", "this is Hadi (m.)"],
        ["Esta é a Ana.", "this is Ana (f.)"],
        ["Apresento-te…", "let me introduce… (tu)"],
        ["Muito prazer!", "pleased to meet you"],
      ],
      note: "este → homem / coisa masculina · esta → mulher / coisa feminina",
      say: "Este é o Hadi. Esta é a Ana. Muito prazer!",
      ms: 8000,
    },
    {
      kind: "table",
      kicker: "RELAÇÕES",
      rows: [
        ["o marido", "a mulher"],
        ["o namorado", "a namorada"],
        ["o amigo", "a amiga"],
        ["o colega", "a colega"],
      ],
      note: "o colega / a colega: a palavra não muda, só o artigo.",
      say: "O marido, a mulher. O namorado, a namorada.",
      ms: 7500,
    },
    { kind: "rule", kicker: "CONHECER", big: "Eu conheço · tu conheces", note: "Já conheces o Hadi? — Conheço, sim! (eu conheço, com ç)", say: "Já conheces o Hadi? Conheço, sim.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.esta_namorada", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.eu_conheco", ms: 7000 },
    { kind: "summary", rows: [["ele", "Este é…"], ["ela", "Esta é…"], ["resposta", "Muito prazer!"]], ms: 5000 },
  ],
  "u02.verbos_er": [
    { kind: "title", big: "Bebes um café?", small: "Verbos regulares em -ER", say: "Bebes um café? Bebo, sim.", ms: 3800 },
    {
      kind: "table",
      kicker: "COMER",
      rows: [
        ["eu", "como"],
        ["tu", "comes"],
        ["ele · ela · você", "come"],
        ["nós", "comemos"],
        ["eles · elas · vocês", "comem"],
      ],
      note: "O mesmo padrão: beber, viver, aprender, perceber, escrever.",
      say: "Eu como, tu comes, ele come, nós comemos, eles comem.",
      ms: 8000,
    },
    { kind: "rule", kicker: "-AR vs -ER", big: "falamos · comemos", note: "Nós: -ar → -amos, -er → -emos. Eles: -am → -em.", say: "Nós falamos. Nós comemos.", ms: 6500 },
    { kind: "example", kicker: "RESPOSTA CURTA", big: "— Bebes um café? — Bebo, sim.", note: "Em português responde-se com o verbo, não só “sim”.", emoji: "☕", say: "Bebes um café? Bebo, sim.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.nos_vivemos", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.bebo_sim", ms: 7000 },
    { kind: "summary", rows: [["eu / tu", "-o / -es"], ["ele", "-e"], ["nós", "-emos"], ["eles", "-em"]], ms: 5000 },
  ],
  "u02.familia": [
    { kind: "title", big: "Esta é a minha mãe", small: "A família e os possessivos", say: "Esta é a minha mãe.", ms: 3800 },
    {
      kind: "table",
      kicker: "A FAMÍLIA",
      rows: [
        ["o pai · a mãe", "os pais (parents)"],
        ["o filho · a filha", "os filhos"],
        ["o irmão · a irmã", "os irmãos"],
        ["o avô · a avó", "os avós"],
        ["o neto · a neta", "os netos"],
        ["o tio · a tia", "os tios"],
      ],
      note: "O plural masculino junta os dois: os pais = o pai + a mãe.",
      say: "O pai, a mãe, os pais. O avô, a avó, os avós.",
      ms: 9000,
    },
    {
      kind: "table",
      kicker: "POSSESSIVOS",
      rows: [
        ["eu", "o meu · a minha · os meus · as minhas"],
        ["tu", "o teu · a tua · os teus · as tuas"],
        ["você", "o seu · a sua"],
        ["nós", "o nosso · a nossa"],
        ["ele / ela", "o pai dele · a mãe dela"],
      ],
      note: "Concorda com a coisa, não com o dono: o Hadi diz “a minha mãe”.",
      say: "O meu pai, a minha mãe. A mãe dele, o pai dela.",
      ms: 9000,
    },
    { kind: "rule", kicker: "DELE / DELA", big: "a casa dela", note: "Para ele / ela, o possessivo vem DEPOIS: o carro dele, os pais dela.", say: "O carro dele. Os pais dela.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.a_minha_mae", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.os_meus_avos", ms: 7000 },
    { kind: "summary", rows: [["a mãe", "a minha mãe"], ["os avós", "os meus avós"], ["ele / ela", "dele / dela"]], ms: 5000 },
  ],
  "u02.sala_aula": [
    { kind: "title", big: "Onde está o meu livro?", small: "A sala de aula, estar e lugares", say: "Onde está o meu livro?", ms: 3800 },
    {
      kind: "table",
      kicker: "VERBO ESTAR",
      rows: [
        ["eu", "estou"],
        ["tu", "estás"],
        ["ele · ela · você", "está"],
        ["nós", "estamos"],
        ["eles · elas · vocês", "estão"],
      ],
      note: "Onde está…? — localização de pessoas e objetos.",
      say: "Eu estou, tu estás, ele está, nós estamos, eles estão.",
      ms: 8000,
    },
    {
      kind: "table",
      kicker: "ONDE?",
      rows: [
        ["em cima de", "on"],
        ["debaixo de", "under"],
        ["dentro de", "inside"],
        ["ao lado de", "next to"],
        ["em frente de · atrás de", "in front of · behind"],
        ["entre", "between"],
      ],
      note: "de + o = do · de + a = da: em cima da mesa, dentro do estojo.",
      say: "O livro está em cima da mesa. A mochila está debaixo da cadeira.",
      ms: 9000,
    },
    { kind: "rule", kicker: "ISTO · ISSO · AQUILO", big: "O que é isto?", note: "Para coisas sem nome: isto (aqui), isso (aí), aquilo (ali). — É um caderno.", say: "O que é isto? É um caderno.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.livro_esta", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.debaixo_da_cadeira", ms: 7000 },
    { kind: "summary", rows: [["estar", "estou · está · estão"], ["de + a mesa", "em cima da mesa"], ["de + o estojo", "dentro do estojo"]], ms: 5000 },
  ],
  "u02.numeros": [
    { kind: "title", big: "30 · 50 · 100", small: "Números até 199", say: "Trinta, cinquenta, cem.", ms: 3600 },
    {
      kind: "table",
      kicker: "AS DEZENAS",
      rows: [
        ["30 · 40", "trinta · quarenta"],
        ["50 · 60", "cinquenta · sessenta"],
        ["70 · 80", "setenta · oitenta"],
        ["90 · 100", "noventa · cem"],
      ],
      say: "Trinta, quarenta, cinquenta, sessenta, setenta, oitenta, noventa, cem.",
      ms: 8000,
    },
    {
      kind: "table",
      kicker: "COM “E”",
      rows: [
        ["21", "vinte e um"],
        ["38", "trinta e oito"],
        ["101", "cento e um"],
        ["199", "cento e noventa e nove"],
      ],
      note: "100 = cem · 101 a 199 = cento e…",
      say: "Vinte e um. Trinta e oito. Cento e um. Cento e noventa e nove.",
      ms: 8000,
    },
    { kind: "rule", kicker: "OUVE BEM", big: "sessenta ≠ setenta", note: "60 tem “ss”, 70 tem “t”.", say: "Sessenta. Setenta.", ms: 5500 },
    { kind: "check", itemId: "grammar.frame.mae_sessenta", ms: 7000 },
    { kind: "check", itemId: "vocab.number.n101", ms: 7000 },
    { kind: "summary", rows: [["60 / 70", "sessenta / setenta"], ["100", "cem"], ["101–199", "cento e…"]], ms: 4500 },
  ],
  "u02.descrever": [
    { kind: "title", big: "Ela é alta e simpática", small: "Descrever pessoas: ser e estar", say: "Ela é alta e simpática.", ms: 3800 },
    {
      kind: "table",
      kicker: "COMO É?",
      rows: [
        ["alto · baixo", "tall · short"],
        ["magro · gordo", "slim · fat"],
        ["simpático · antipático", "nice · unfriendly"],
        ["tímido · sociável", "shy · sociable"],
        ["trabalhador · preguiçoso", "hard-working · lazy"],
      ],
      note: "O adjetivo concorda: o Rui é alto, a Ana é alta, elas são altas.",
      say: "Alto, baixo. Simpático, antipático.",
      ms: 9000,
    },
    {
      kind: "table",
      kicker: "SER OU ESTAR?",
      rows: [
        ["SER — permanente", "Sou solteira. Ele é alto."],
        ["ESTAR — agora", "Hoje estou cansado."],
        ["SER — lugar fixo", "A casa é no centro."],
        ["ESTAR — lugar agora", "Ela está na escola."],
      ],
      note: "Estado civil e profissão → sempre SER.",
      say: "Ele é alto. Hoje estou cansado.",
      ms: 9000,
    },
    { kind: "rule", kicker: "CABELO E ÓCULOS", big: "Tem cabelo curto e usa óculos.", note: "O cabelo é com TER; os óculos com USAR.", say: "Tem cabelo curto e usa óculos.", ms: 6000 },
    { kind: "check", itemId: "grammar.frame.hoje_estou", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.amigas_simpaticas", ms: 7000 },
    { kind: "summary", rows: [["permanente", "ser"], ["agora", "estar"], ["cabelo", "ter"]], ms: 5000 },
  ],
  "u02.passatempos": [
    { kind: "title", big: "Gosto de dançar!", small: "Passatempos, aprender e perceber", say: "O que gostas de fazer? Gosto de dançar.", ms: 3800 },
    {
      kind: "table",
      kicker: "GOSTAR DE + INFINITIVO",
      rows: [
        ["Gosto de ler.", "I like reading"],
        ["Gosto de pintar.", "I like painting"],
        ["Gosto de jogar futebol.", "I like playing football"],
        ["Gosto de ir ao cinema.", "I like going to the cinema"],
      ],
      note: "Depois de “gostar de”, o verbo fica no infinitivo (-ar, -er, -ir).",
      say: "Gosto de ler. Gosto de pintar. Gosto de ir ao cinema.",
      ms: 8500,
    },
    {
      kind: "table",
      kicker: "APRENDER · PERCEBER",
      rows: [
        ["eu", "aprendo · percebo"],
        ["tu", "aprendes · percebes"],
        ["ele · ela", "aprende · percebe"],
        ["nós", "aprendemos · percebemos"],
        ["eles · elas", "aprendem · percebem"],
      ],
      note: "Não percebo! — perceber é o verbo do dia a dia em Portugal.",
      say: "Eu aprendo português. Não percebo.",
      ms: 8500,
    },
    { kind: "check", itemId: "grammar.frame.eu_aprendo", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.gosto_de", ms: 7000 },
    { kind: "summary", rows: [["gostar", "de + infinitivo"], ["eu", "aprendo · percebo"], ["eles", "aprendem · percebem"]], ms: 5000 },
  ],
  "pds1.revisao": [
    { kind: "title", big: "Ponto da Situação 1", small: "Revisão: Unidades 0, 1 e 2", say: "Ponto da situação!", ms: 3600 },
    {
      kind: "table",
      kicker: "RESPOSTAS CURTAS",
      rows: [
        ["Vocês falam português?", "Falamos, sim."],
        ["Conheces a Ana?", "Conheço, sim."],
        ["A Ana está em casa?", "Está, sim."],
      ],
      note: "Repete o verbo na pessoa certa.",
      say: "Vocês falam português? Falamos, sim.",
      ms: 8000,
    },
    {
      kind: "table",
      kicker: "PERGUNTAS",
      rows: [
        ["Como?", "Como te chamas?"],
        ["De onde?", "De onde és?"],
        ["Onde?", "Onde vives?"],
        ["Quantos / Quantas?", "Quantos anos tens? · Quantas irmãs tens?"],
      ],
      say: "Como te chamas? De onde és? Onde vives? Quantos anos tens?",
      ms: 8500,
    },
    { kind: "rule", kicker: "SER vs ESTAR", big: "É simpática · Está em casa", note: "Característica → ser. Onde está agora → estar.", say: "Ela é simpática. Ela está em casa.", ms: 6000 },
    { kind: "check", itemId: "grammar.frame.falamos", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.quantos_anos", ms: 7000 },
    { kind: "summary", rows: [["um / uma", "artigo indefinido"], ["os irmãos", "plural +s"], ["agora / lugar", "estar"]], ms: 5000 },
  ],
  "trab1.colegas": [
    { kind: "title", big: "Muito gosto!", small: "No trabalho: formal e informal", say: "Muito gosto, Doutora Rita!", ms: 3800 },
    {
      kind: "table",
      kicker: "FORMAL · INFORMAL",
      rows: [
        ["Muito gosto, Dra. Rita!", "formal"],
        ["Prazer em conhecer-te!", "informal (tu)"],
        ["Igualmente.", "likewise — os dois"],
        ["O Sr. Costa está?", "is Mr Costa in?"],
        ["Um momento, por favor.", "one moment, please"],
      ],
      note: "Formal: o Sr. / a Sra. / o Dr. / a Dra. + apelido.",
      say: "Muito gosto. Igualmente. Um momento, por favor.",
      ms: 9000,
    },
    {
      kind: "table",
      kicker: "PROCURA-SE…",
      rows: [
        ["organizado / organizada", "organised"],
        ["atento / atenta", "attentive"],
        ["paciente", "patient"],
        ["comunicativo / comunicativa", "outgoing"],
      ],
      note: "Num anúncio: Procura-se rececionista. Deve ser paciente e organizado.",
      say: "Procura-se rececionista. Deve ser paciente e organizado.",
      ms: 8500,
    },
    { kind: "rule", kicker: "AQUELE", big: "Aquele senhor ali é o diretor?", note: "Longe (ali) → aquele / aquela · aqui → este / esta.", say: "Aquele senhor ali é o diretor?", ms: 6000 },
    { kind: "check", itemId: "grammar.frame.aquele_senhor", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.prazer_conhecer_te", ms: 7000 },
    { kind: "summary", rows: [["formal", "Muito gosto · Sr. / Dra."], ["informal", "Prazer em conhecer-te"], ["ali", "aquele / aquela"]], ms: 5000 },
  ],
  "mundo1.lusofonia": [
    { kind: "title", big: "Onde se fala português?", small: "O mundo do português: a CPLP", say: "Onde se fala português?", ms: 3800 },
    {
      kind: "table",
      kicker: "PAÍSES DA CPLP",
      rows: [
        ["🇵🇹 Portugal · 🇧🇷 Brasil", "português · brasileiro"],
        ["🇦🇴 Angola · 🇲🇿 Moçambique", "angolano · moçambicano"],
        ["🇨🇻 Cabo Verde · Guiné-Bissau", "cabo-verdiano · guineense"],
        ["🇸🇹 São Tomé e Príncipe", "são-tomense"],
        ["🇹🇱 Timor-Leste · Guiné Equatorial", "timorense · equato-guineense"],
      ],
      note: "Também se fala português em Macau e em Goa (Índia).",
      say: "Portugal, Brasil, Angola, Moçambique, Cabo Verde, Guiné-Bissau, São Tomé e Príncipe, Timor-Leste.",
      ms: 9500,
    },
    { kind: "example", kicker: "5 DE MAIO", big: "Dia Mundial da Língua Portuguesa", note: "Celebra-se a 5 de maio em todos os países de língua portuguesa.", emoji: "📅", say: "O Dia Mundial da Língua Portuguesa é a cinco de maio.", ms: 6000 },
    { kind: "rule", kicker: "DE ONDE ÉS?", big: "Sou de Cabo Verde · Sou do Brasil", note: "Sem artigo: Portugal, Angola, Moçambique, Cabo Verde. Com artigo: o Brasil → do Brasil.", say: "Sou de Cabo Verde. Sou do Brasil.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.de_cabo_verde", ms: 7000 },
    { kind: "check", itemId: "vocab.nationality.mocambique", ms: 7000 },
    { kind: "summary", rows: [["CPLP", "9 países"], ["5 de maio", "Dia da Língua Portuguesa"], ["Cabo Verde", "cabo-verdiano / cabo-verdiana"]], ms: 5000 },
  ],
};
