/** Unit 8 lessons (and the review / world sections that follow it), in book order, plus their tip cards. */
import type { AulaStep } from "../aulas.ts";
import type { Lesson } from "../schema.ts";

type Unit = "u08" | "pds4" | "trab4" | "mundo4";
const pav = (unit: Unit, pages: number[], concept: string) => ({ sourceId: "pav1-student" as const, unit, pages, concept });
const fn = (unit: Unit, ...slugs: string[]) => slugs.map((s) => `function.${unit}.${s}`);
const nouns = (...slugs: string[]) => slugs.map((s) => `vocab.noun.${s}`);
const adjs = (...slugs: string[]) => slugs.map((s) => `vocab.adjective.${s}`);
const frames = (...slugs: string[]) => slugs.map((s) => `grammar.frame.${s}`);
const errors = (...slugs: string[]) => slugs.map((s) => `grammar.error.${s}`);
const pps = (verb: string, ...persons: string[]) => (persons.length ? persons : ["eu", "tu", "ele", "nos", "eles"]).map((p) => `grammar.${verb}.pps.${p}`);

export const U08_LESSONS: Lesson[] = [
  {
    id: "u08.ferias",
    unit: "u08",
    title: "Aonde vais nas férias? — férias e preferências",
    source: pav("u08", [190, 191, 192, 193], "holidays-preferences"),
    itemIds: [
      ...nouns("viagem", "ilha", "campo", "por_do_sol", "aldeia"),
      ...fn("u08", "aonde_vais_ferias", "vou_passar_ferias", "prefiro_praia", "gosto_mais_campo", "viajo_de_comboio", "ja_experimentaste", "ainda_nao_interessada", "ja_e_adorei", "nunca_sem_interesse", "ouvi_dizer", "tens_de_voltar", "foi_divertido"),
      ...frames("prefiro_praia", "andar_de_aviao", "ainda_nao"),
    ],
    canDo: ["cd20.travel", "cd06.routines", "cd19.past"],
  },
  {
    id: "u08.pps_ar",
    unit: "u08",
    title: "Viajei, visitei, fiquei — o passado dos verbos em -ar",
    source: pav("u08", [194, 195, 205], "pps-regular-ar"),
    itemIds: [...pps("viajar"), ...pps("visitar"), ...pps("ficar"), ...frames("viajei", "visitamos", "fiquei", "ficaste"), ...errors("ficei")],
    canDo: ["cd19.past"],
  },
  {
    id: "u08.pps_er_ir",
    unit: "u08",
    title: "Comi, conheci, parti — o passado em -er e -ir",
    source: pav("u08", [194, 195, 205], "pps-regular-er-ir"),
    itemIds: [...pps("comer"), ...pps("conhecer"), ...pps("partir"), ...frames("comi", "conheceste", "comeram", "partiu", "partimos")],
    canDo: ["cd19.past"],
  },
  {
    id: "u08.fui_estive_tive",
    unit: "u08",
    title: "Fui, estive, tive — ir, estar e ter no passado",
    source: pav("u08", [196, 205], "pps-irregular-ir-estar-ter"),
    itemIds: [...pps("ir"), ...pps("estar"), ...pps("ter"), ...frames("fui_cinema", "estiveste", "tempo_esteve", "tivemos_sorte", "teve_de_voltar")],
    canDo: ["cd19.past", "cd20.travel"],
  },
  {
    id: "u08.foi_otimo",
    unit: "u08",
    title: "Foi ótimo! — ser, fazer e ver no passado",
    source: pav("u08", [196, 205], "pps-irregular-ser-fazer-ver"),
    itemIds: [...pps("ser"), ...pps("fazer"), ...pps("ver"), ...frames("viagem_foi", "pessoas_foram", "fizeste", "vimos_golfinhos"), ...errors("fazeste")],
    canDo: ["cd19.past"],
  },
  {
    id: "u08.ontem",
    unit: "u08",
    title: "Ontem, há dois anos — contar o passado",
    source: pav("u08", [194, 197, 198, 199], "past-time-expressions"),
    itemIds: [
      ...fn("u08", "onde_estiveste", "o_que_fizeste", "como_correram", "foram_otimas", "ja_estiveste_cv", "ainda_nao_fui", "nunca_fui_acores", "choveu_um_pouco", "nasci_em", "ontem", "na_semana_passada", "no_ano_passado", "ha_dois_anos", "em_2019"),
      ...frames("nunca_fui", "ha_dois_anos", "semana_passada", "normalmente_ontem"),
      ...errors("ontem_vamos", "desde_tres_anos"),
    ],
    canDo: ["cd19.past", "cd07.numbers-prices"],
  },
  {
    id: "u08.hotel_aeroporto",
    unit: "u08",
    title: "No hotel e no aeroporto — viajar",
    source: pav("u08", [196, 197, 198, 211], "hotel-airport"),
    itemIds: [
      ...nouns("passaporte", "aeroporto", "chave"),
      ...fn("u08", "tenho_uma_reserva", "queria_quarto_duplo", "pequeno_almoco_incluido", "deixar_as_malas", "a_que_horas_check_out", "o_seu_passaporte", "voo_atrasado", "apanhei_o_aviao", "alugamos_um_carro", "tirei_fotografias", "ja_fiz_as_malas"),
      ...frames("apanhei_aviao", "deixar_malas_rececao", "reservei_quarto"),
      ...errors("pagei"),
    ],
    canDo: ["cd20.travel", "cd19.past"],
  },
  {
    id: "pds4.quatro_tempos",
    unit: "pds4",
    title: "Agora, sempre, ontem, amanhã — os quatro tempos",
    source: pav("pds4", [206, 207], "tense-frames"),
    itemIds: [
      ...fn("pds4", "neste_momento", "normalmente", "na_proxima_semana", "pela_primeira_vez"),
      ...fn("u08", "anteontem", "no_fim_de_semana_passado"),
      ...frames("tempo_agora", "tempo_normalmente", "tempo_ontem", "tempo_amanha", "tempo_passado_foi"),
      ...errors("estou_a_trabalhei"),
    ],
    canDo: ["cd19.past", "cd15.future-plans", "cd06.routines"],
  },
  {
    id: "pds4.revisao",
    unit: "pds4",
    title: "Ponto da Situação 4 — revisão das Unidades 7 e 8",
    source: pav("pds4", [206, 207, 208, 209, 210, 211], "review-units-7-8"),
    itemIds: [
      ...pps("viajar", "nos"),
      ...pps("comer", "eu"),
      ...pps("ir", "eu"),
      ...pps("estar", "ele"),
      ...pps("ter", "eu"),
      ...pps("fazer", "eu"),
      "function.u07.quantos_anos_fazes",
      "function.u07.queres_vir_festa",
      "function.u07.boa_viagem",
      "function.u08.como_correram",
      ...frames("foram_cv", "fiz_caminhada", "indef_nenhum", "tanto_tempo"),
      ...errors("viajamos_passado", "fui_doente"),
    ],
    canDo: ["cd19.past", "cd17.invitations", "cd18.festivals"],
  },
  {
    id: "trab4.entrevista",
    unit: "trab4",
    title: "O currículo e a entrevista de emprego",
    source: pav("trab4", [212, 213], "cv-job-interview"),
    itemIds: [
      ...nouns("curriculo"),
      ...fn("trab4", "pode_sentar_se", "qual_a_sua_formacao", "tem_experiencia", "porque_quer_mudar", "pode_comecar", "trabalhei_tres_anos", "vivo_ha_cinco_anos", "falo_tres_linguas", "dizemos_lhe_algo", "fico_a_aguardar"),
      ...frames("a_sua_nacionalidade", "ha_cinco_anos", "mudar_de_emprego"),
      ...errors("o_sua_formacao"),
    ],
    canDo: ["cd21.forms", "cd02.personal-info", "cd19.past"],
  },
  {
    id: "mundo4.cabo_verde",
    unit: "mundo4",
    title: "Cabo Verde — dez ilhas no Atlântico",
    source: pav("mundo4", [214, 215, 216], "cabo-verde"),
    itemIds: [
      ...nouns("ilha", "vulcao", "tartaruga", "tambor"),
      ...adjs("seco", "humido", "cheio", "vazio"),
      ...fn("mundo4", "dez_ilhas", "capital_praia", "fala_se_crioulo", "clima_quente_seco", "pico_do_fogo", "carnaval_mindelo", "morna"),
      ...frames("cv_no_atlantico", "lingua_oficial", "maior_ilha"),
    ],
    canDo: ["cd18.festivals", "cd14.weather-clothes", "cd22.listen-clear"],
  },
];

export const U08_AULAS: Record<string, AulaStep[]> = {
  "u08.ferias": [
    { kind: "title", big: "Aonde vais nas férias?", small: "Férias, viagens e preferências", say: "Já sabes aonde vais nas férias?", ms: 3800 },
    {
      kind: "table",
      kicker: "PREFERÊNCIAS",
      rows: [
        ["Prefiro a praia à montanha.", "preferir A a B"],
        ["Gosto mais de ficar no campo.", "gostar mais de"],
        ["Gosto de andar de comboio.", "andar de + transporte"],
        ["Adoro conhecer outras culturas.", "adorar"],
      ],
      say: "Prefiro a praia à montanha. Gosto mais de ficar no campo.",
      ms: 8000,
    },
    {
      kind: "table",
      kicker: "JÁ EXPERIMENTASTE?",
      rows: [
        ["Já, e adorei!", "yes, and I loved it"],
        ["Ainda não, mas estou interessado/a.", "not yet"],
        ["Nunca, e não tenho interesse.", "never"],
      ],
      say: "Já experimentaste mergulho? Ainda não.",
      ms: 7500,
    },
    { kind: "check", itemId: "grammar.frame.prefiro_praia", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.ainda_nao", ms: 7000 },
    { kind: "summary", rows: [["preferir", "prefiro A a B"], ["já / ainda não / nunca", "+ passado"], ["andar de", "avião · comboio · barco"]], ms: 5000 },
  ],
  "u08.pps_ar": [
    { kind: "title", big: "Viajei para os Açores", small: "Pretérito Perfeito: verbos em -AR", say: "No verão passado, viajei para os Açores.", ms: 3800 },
    {
      kind: "table",
      kicker: "VIAJAR — PASSADO",
      rows: [
        ["eu", "viajei"],
        ["tu", "viajaste"],
        ["ele · ela · você", "viajou"],
        ["nós", "viajámos"],
        ["eles · elas · vocês", "viajaram"],
      ],
      note: "Ações acabadas no passado: ontem, na semana passada, no ano passado.",
      say: "Viajei, viajaste, viajou, viajámos, viajaram.",
      ms: 8000,
    },
    { kind: "rule", kicker: "ATENÇÃO AO ACENTO", big: "viajamos ≠ viajámos", note: "Presente: viajamos. Passado: viajámos (com acento, em Portugal).", say: "Normalmente viajamos. No ano passado viajámos.", ms: 6500 },
    { kind: "rule", kicker: "ORTOGRAFIA", big: "ficar → fiquei · pagar → paguei", note: "Só no eu: c → qu, g → gu antes de e.", say: "Fiquei em casa. Paguei o hotel.", ms: 6000 },
    { kind: "check", itemId: "grammar.frame.visitamos", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.fiquei", ms: 7000 },
    { kind: "summary", rows: [["eu", "-ei"], ["tu", "-aste"], ["ele", "-ou"], ["nós", "-ámos"], ["eles", "-aram"]], ms: 5000 },
  ],
  "u08.pps_er_ir": [
    { kind: "title", big: "Comi e parti", small: "Pretérito Perfeito: -ER e -IR", say: "Comi peixe e parti cedo.", ms: 3800 },
    {
      kind: "table",
      kicker: "-ER · -IR",
      rows: [
        ["eu", "comi · parti"],
        ["tu", "comeste · partiste"],
        ["ele · ela · você", "comeu · partiu"],
        ["nós", "comemos · partimos"],
        ["eles · elas · vocês", "comeram · partiram"],
      ],
      say: "Comi, comeste, comeu. Parti, partiste, partiu.",
      ms: 8000,
    },
    { kind: "rule", kicker: "NÓS", big: "comemos · partimos", note: "Igual ao presente! A palavra de tempo (ontem, normalmente) decide.", say: "Ontem comemos fora.", ms: 6000 },
    { kind: "check", itemId: "grammar.frame.conheceste", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.partiu", ms: 7000 },
    { kind: "summary", rows: [["-er", "-i · -este · -eu · -emos · -eram"], ["-ir", "-i · -iste · -iu · -imos · -iram"]], ms: 5000 },
  ],
  "u08.fui_estive_tive": [
    { kind: "title", big: "Fui a Cabo Verde", small: "Irregulares: ir, estar, ter", say: "Fui a Cabo Verde e estive lá duas semanas.", ms: 3800 },
    {
      kind: "table",
      kicker: "IR · ESTAR · TER",
      rows: [
        ["eu", "fui · estive · tive"],
        ["tu", "foste · estiveste · tiveste"],
        ["ele · ela · você", "foi · esteve · teve"],
        ["nós", "fomos · estivemos · tivemos"],
        ["eles · elas · vocês", "foram · estiveram · tiveram"],
      ],
      say: "Fui, estive, tive. Foi, esteve, teve.",
      ms: 9000,
    },
    { kind: "rule", kicker: "O TEMPO", big: "Esteve sempre calor.", note: "Para o tempo e para estadias: esteve bom, estive duas semanas.", say: "O tempo esteve ótimo.", ms: 6000 },
    { kind: "check", itemId: "grammar.frame.fui_cinema", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.tempo_esteve", ms: 7000 },
    { kind: "summary", rows: [["ir", "fui · foi · foram"], ["estar", "estive · esteve"], ["ter", "tive · teve"]], ms: 5000 },
  ],
  "u08.foi_otimo": [
    { kind: "title", big: "Foi ótimo!", small: "Irregulares: ser, fazer, ver", say: "Foi ótimo! Fiz uma caminhada e vi golfinhos.", ms: 3800 },
    {
      kind: "table",
      kicker: "SER · FAZER · VER",
      rows: [
        ["eu", "fui · fiz · vi"],
        ["tu", "foste · fizeste · viste"],
        ["ele · ela · você", "foi · fez · viu"],
        ["nós", "fomos · fizemos · vimos"],
        ["eles · elas · vocês", "foram · fizeram · viram"],
      ],
      note: "ser e ir têm o mesmo passado: A viagem foi ótima. / Fui à praia.",
      say: "Fui, fiz, vi. Foi, fez, viu.",
      ms: 9000,
    },
    { kind: "rule", kicker: "SER OU ESTAR?", big: "A festa foi ótima. · Estive doente.", note: "ser → como foi (opinião); estar → estado ou lugar passageiro.", say: "A festa foi ótima. Estive doente.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.viagem_foi", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.fizeste", ms: 7000 },
    { kind: "summary", rows: [["ser", "foi · foram"], ["fazer", "fiz · fez"], ["ver", "vi · viu"]], ms: 5000 },
  ],
  "u08.ontem": [
    { kind: "title", big: "Ontem, há dois anos…", small: "Falar do passado", say: "O que fizeste ontem?", ms: 3800 },
    {
      kind: "table",
      kicker: "QUANDO? (PASSADO)",
      rows: [
        ["ontem · anteontem", "yesterday · the day before"],
        ["na semana passada", "last week"],
        ["no fim de semana passado", "last weekend"],
        ["no ano passado", "last year"],
        ["há dois anos", "two years ago"],
        ["em 2019", "em dois mil e dezanove"],
      ],
      say: "Ontem. Na semana passada. Há dois anos.",
      ms: 9000,
    },
    { kind: "table", kicker: "JÁ · AINDA NÃO · NUNCA", rows: [["Já estiveste em Cabo Verde?", "have you ever been…?"], ["Ainda não fui.", "not yet"], ["Nunca fui aos Açores.", "never"]], say: "Já estiveste em Cabo Verde? Ainda não fui.", ms: 7500 },
    { kind: "check", itemId: "grammar.frame.ha_dois_anos", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.normalmente_ontem", ms: 7000 },
    { kind: "summary", rows: [["normalmente", "presente"], ["ontem / há … anos", "passado"], ["há + tempo", "= ago"]], ms: 5000 },
  ],
  "u08.hotel_aeroporto": [
    { kind: "title", big: "Tenho uma reserva", small: "No hotel e no aeroporto", say: "Boa tarde, tenho uma reserva.", ms: 3800 },
    {
      kind: "table",
      kicker: "NO HOTEL",
      rows: [
        ["Tenho uma reserva em nome de…", "I have a booking under…"],
        ["Queria um quarto duplo.", "I'd like a double room"],
        ["O pequeno-almoço está incluído?", "is breakfast included?"],
        ["Posso deixar as malas na receção?", "can I leave my bags?"],
        ["A que horas é o check-out?", "what time is check-out?"],
      ],
      say: "Tenho uma reserva. O pequeno-almoço está incluído?",
      ms: 9000,
    },
    { kind: "table", kicker: "NA VIAGEM", rows: [["apanhar", "o avião · o comboio"], ["alugar", "um carro"], ["fazer", "as malas · o check-in"], ["tirar", "fotografias"]], say: "Apanhei o avião. Alugámos um carro.", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.apanhei_aviao", ms: 7000 },
    { kind: "check", itemId: "function.u08.pequeno_almoco_incluido", ms: 7000 },
    { kind: "summary", rows: [["hotel", "reserva · quarto · receção"], ["aeroporto", "passaporte · voo · check-in"]], ms: 5000 },
  ],
  "pds4.quatro_tempos": [
    { kind: "title", big: "Agora, sempre, ontem, amanhã", small: "Quatro tempos para um verbo", say: "Estou a jantar. Janto. Jantei. Vou jantar.", ms: 3800 },
    {
      kind: "table",
      kicker: "UM VERBO, QUATRO TEMPOS",
      rows: [
        ["agora · neste momento", "estou a jantar"],
        ["normalmente · sempre", "janto"],
        ["ontem · há dois dias", "jantei"],
        ["amanhã · na próxima semana", "vou jantar"],
      ],
      say: "Neste momento estou a jantar. Normalmente janto às oito. Ontem jantei às dez. Amanhã vou jantar fora.",
      ms: 9000,
    },
    { kind: "rule", kicker: "NÓS", big: "jantamos ≠ jantámos", note: "Presente sem acento, passado com acento.", say: "Normalmente jantamos às oito. Ontem jantámos às dez.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.tempo_agora", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.tempo_ontem", ms: 7000 },
    { kind: "summary", rows: [["agora", "estar a + infinitivo"], ["hábito", "presente"], ["passado", "pretérito perfeito"], ["futuro", "ir + infinitivo"]], ms: 5000 },
  ],
  "pds4.revisao": [
    { kind: "title", big: "Ponto da Situação 4", small: "Revisão: festas, convites e férias", say: "Como correram as férias?", ms: 3800 },
    {
      kind: "table",
      kicker: "REVISÃO",
      rows: [
        ["Quantos anos fazes?", "fazer anos"],
        ["Queres vir à minha festa?", "convidar"],
        ["Boa viagem!", "votos"],
        ["Fui · estive · tive · fiz", "passado irregular"],
        ["viajei · comi · parti", "passado regular"],
        ["há dois anos", "= ago"],
      ],
      say: "Quantos anos fazes? Queres vir à minha festa? Boa viagem!",
      ms: 9000,
    },
    { kind: "check", itemId: "grammar.error.fui_doente", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.foram_cv", ms: 7000 },
    { kind: "summary", rows: [["-ar", "-ei · -ou · -ámos"], ["-er / -ir", "-i · -eu / -iu"], ["ir / ser", "fui · foi · foram"]], ms: 5000 },
  ],
  "trab4.entrevista": [
    { kind: "title", big: "Pode sentar-se.", small: "O currículo e a entrevista", say: "Bom dia. Pode sentar-se, por favor.", ms: 3800 },
    {
      kind: "table",
      kicker: "PERGUNTAS DA ENTREVISTA",
      rows: [
        ["Qual é a sua nacionalidade?", "nationality"],
        ["Qual é a sua formação?", "education"],
        ["Tem experiência em…?", "experience"],
        ["Porque é que quer mudar de emprego?", "reason"],
        ["Pode começar no próximo mês?", "availability"],
      ],
      note: "Formal: você / a sua — sem pronome, com o verbo na 3.ª pessoa.",
      say: "Qual é a sua formação? Tem experiência?",
      ms: 9000,
    },
    { kind: "table", kicker: "O CURRÍCULO", rows: [["dados pessoais", "nome · morada · telemóvel · e-mail"], ["formação académica", "ensino secundário · superior"], ["experiência profissional", "empresa · função"], ["idiomas", "línguas que fala"]], say: "Dados pessoais. Formação académica. Experiência profissional.", ms: 8000 },
    { kind: "rule", kicker: "HÁ + TEMPO", big: "Vivo cá há cinco anos. · Há dois anos, fiz um curso.", note: "presente + há = for (até hoje) · passado + há = ago", say: "Vivo em Portugal há cinco anos.", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.a_sua_nacionalidade", ms: 7000 },
    { kind: "check", itemId: "grammar.frame.ha_cinco_anos", ms: 7000 },
    { kind: "summary", rows: [["formal", "a sua · o seu · pode…?"], ["experiência", "trabalhei … anos"]], ms: 5000 },
  ],
  "mundo4.cabo_verde": [
    { kind: "title", big: "Cabo Verde", small: "Dez ilhas no Atlântico", say: "Cabo Verde tem dez ilhas.", ms: 3800 },
    {
      kind: "table",
      kicker: "CABO VERDE",
      rows: [
        ["onde?", "no oceano Atlântico, perto da costa africana"],
        ["ilhas", "dez (nove habitadas)"],
        ["capital", "a Praia, na ilha de Santiago"],
        ["línguas", "português (oficial) e crioulo"],
        ["clima", "quente e seco"],
        ["Pico do Fogo", "vulcão ativo"],
      ],
      say: "Cabo Verde tem dez ilhas. A capital é a Praia.",
      ms: 9000,
    },
    { kind: "rule", kicker: "FESTAS", big: "Carnaval, São João, Tabanka", note: "O Carnaval do Mindelo é famoso; no São João há tambores e dança na rua.", say: "O Carnaval do Mindelo é muito famoso.", ms: 6500 },
    { kind: "check", itemId: "grammar.frame.maior_ilha", ms: 7000 },
    { kind: "check", itemId: "function.mundo4.fala_se_crioulo", ms: 7000 },
    { kind: "summary", rows: [["capital", "Praia"], ["maior ilha", "Santiago"], ["línguas", "português e crioulo"]], ms: 5000 },
  ],
};
