/**
 * Stop! reference words: common A1–A2 European Portuguese words per category, used ONLY for the
 * "other words you could use" suggestions after each letter (never to accept or reject an answer —
 * that's the curriculum dictionary plus the partner's vote). pt-PT forms throughout (sumo, ananás,
 * autocarro, telemóvel, frigorífico, pequeno-almoço, talho, miradouro, Polónia, Quénia…).
 */

/** Common A1–A2 pt-PT words per Stop category, for "other words you could use" suggestions only. Display form (with accents; no article except where natural). */
export const REFERENCE: Record<"comida" | "animal" | "coisa" | "profissao" | "pais" | "lugar", string[]> = {
  comida: [
    "açúcar", "água", "alface", "alho", "almôndega", "ameixa", "amêndoa", "amendoim", "ananás", "arroz", "atum", "azeite", "azeitona",
    "bacalhau", "banana", "batata", "batata frita", "bica", "bife", "bifana", "bolacha", "bolo", "bolo-rei", "broa", "brócolos",
    "café", "caldo verde", "camarão", "caracóis", "carne", "caril", "castanha", "cebola", "cenoura", "cereja", "cerveja", "chá", "chocolate", "chouriço", "cogumelo", "compota", "couve", "cozido", "croissant", "croquete",
    "damasco", "doce",
    "empada",
    "ervilha", "esparguete", "espinafre",
    "farinha", "feijão", "fiambre", "figo", "framboesa", "francesinha", "frango", "fruta",
    "galão", "gelado", "gelatina", "gaspacho", "grão",
    "hambúrguer", "hortelã",
    "iogurte",
    "laranja", "lagosta", "leite", "limão", "limonada", "linguado", "lula",
    "maçã", "manga", "manteiga", "marmelada", "massa", "mel", "melancia", "melão", "morango", "mostarda",
    "nabo", "natas", "noz",
    "omelete", "ovo",
    "pão", "pastel de nata", "patanisca", "peixe", "pepino", "pequeno-almoço", "pera", "pêssego", "pimento", "pizza", "pipoca", "polvo", "presunto", "pudim",
    "queijada", "queijo",
    "rabanada", "requeijão", "rissol",
    "sal", "salada", "salmão", "salsicha", "sandes", "sardinha", "sopa", "sumo",
    "tangerina", "tomate", "torrada", "tosta mista", "tremoço",
    "uva",
    "vinagre", "vinho", "vitela",
  ],
  animal: [
    "abelha", "águia", "alforreca", "andorinha", "aranha", "avestruz",
    "baleia", "bode", "borboleta", "búfalo", "burro",
    "cabra", "camelo", "canguru", "canário", "cão", "caracol", "caranguejo", "carneiro", "cavalo", "cegonha", "cisne", "cobra", "coelho", "coruja", "crocodilo",
    "dinossauro",
    "elefante", "esquilo", "enguia", "estrela-do-mar",
    "falcão", "flamingo", "foca", "formiga",
    "gaivota", "galinha", "galo", "gato", "gafanhoto", "gazela", "girafa", "golfinho", "gorila", "grilo",
    "hamster", "hipopótamo",
    "iguana",
    "jacaré", "javali", "joaninha",
    "lagarto", "lagosta", "leão", "leopardo", "lesma", "lince", "lobo", "lontra", "lula",
    "macaco", "minhoca", "mocho", "morcego", "mosca", "mosquito",
    "orca", "ouriço", "ovelha",
    "panda", "papagaio", "periquito", "pássaro", "pato", "peixe", "pinguim", "polvo", "pombo", "pónei", "porco", "pulga", "peru",
    "rã", "raposa", "rato", "rinoceronte",
    "salmão", "sapo", "sardinha", "serpente",
    "tartaruga", "tigre", "toupeira", "touro", "tubarão",
    "urso",
    "vaca", "veado", "vespa",
    "zebra",
  ],
  coisa: [
    "almofada", "anel", "armário", "aspirador", "autocarro", "avião",
    "balão", "balde", "banco", "barco", "bicicleta", "bola", "boné", "borracha", "botão", "brinco",
    "cadeira", "caderno", "caixa", "cama", "camisola", "caneca", "caneta", "carro", "cachecol", "calças", "carteira", "casaco", "chapéu", "chave", "chávena", "chuveiro", "cinto", "colher", "comboio", "computador", "copo", "cortina",
    "despertador", "dinheiro",
    "elétrico", "envelope", "escova", "escada", "espelho", "estojo",
    "faca", "fogão", "fotografia", "frigideira", "frigorífico",
    "garfo", "garrafa", "gaveta", "guarda-chuva", "guitarra",
    "helicóptero",
    "isqueiro",
    "janela", "jogo", "jornal",
    "lâmpada", "lápis", "livro", "luva",
    "mala", "máquina de lavar", "meia", "mesa", "micro-ondas", "mochila", "moeda", "mota",
    "navio",
    "óculos",
    "panela", "papel", "pente", "piano", "porta", "postal", "prato", "presente", "pulseira",
    "quadro",
    "rádio", "régua", "relógio",
    "sabonete", "saco", "sanita", "sapatilha", "sapato", "secador", "selo", "sofá",
    "tacho", "tapete", "telemóvel", "televisão", "tesoura", "toalha", "torradeira", "trotinete",
    "urso de peluche",
    "vassoura", "vela", "ventoinha", "vestido",
    "xadrez",
  ],
  profissao: [
    "advogado", "agricultor", "apicultor", "arquiteto", "artista", "assistente de bordo", "astronauta", "ator",
    "bailarino", "bancário", "barbeiro", "baterista", "bibliotecário", "biólogo", "bombeiro",
    "cabeleireiro", "calceteiro", "canalizador", "cantor", "carpinteiro", "carteiro", "cientista", "cirurgião", "condutor", "contabilista", "cozinheiro", "costureiro",
    "dentista", "diplomata",
    "economista", "eletricista", "empregado de balcão", "empregado de limpeza", "empregado de mesa", "empresário", "enfermeiro", "engenheiro", "escritor", "estilista", "estudante", "explicador",
    "fadista", "farmacêutico", "fisioterapeuta", "florista", "fotógrafo", "futebolista",
    "gestor", "guia", "guarda-florestal", "guitarrista",
    "historiador",
    "ilustrador", "informático", "intérprete",
    "jardineiro", "jogador", "jornalista", "juiz",
    "lojista",
    "maquinista", "marinheiro", "matemático", "mecânico", "médico", "mergulhador", "merceeiro", "militar", "modelo", "motorista", "músico",
    "nadador-salvador", "nutricionista",
    "operador de caixa", "ourives",
    "padeiro", "pasteleiro", "pastor", "pedreiro", "peixeiro", "pescador", "pianista", "piloto", "pintor", "polícia", "político", "porteiro", "professor", "programador", "psicólogo",
    "químico",
    "realizador", "rececionista",
    "sapateiro", "secretário", "segurança", "soldado", "surfista",
    "talhante", "taxista", "técnico", "tradutor", "treinador",
    "vendedor", "veterinário", "vigilante", "violinista",
  ],
  pais: [
    "Alemanha", "alemão", "Angola", "angolano", "Argentina", "argentino", "Austrália", "australiano", "Áustria", "austríaco",
    "Bélgica", "belga", "Brasil", "brasileiro", "Bulgária", "búlgaro",
    "Cabo Verde", "cabo-verdiano", "Canadá", "canadiano", "Chile", "chileno", "China", "chinês", "Colômbia", "colombiano", "Coreia do Sul", "coreano", "Croácia", "croata", "Cuba", "cubano",
    "Dinamarca", "dinamarquês",
    "Egito", "egípcio", "Escócia", "escocês", "Espanha", "espanhol", "Estados Unidos", "americano", "norte-americano",
    "Finlândia", "finlandês", "França", "francês",
    "Grécia", "grego", "Guiné-Bissau", "guineense",
    "Holanda", "holandês", "Hungria", "húngaro",
    "Índia", "indiano", "Inglaterra", "inglês", "Irão", "iraniano", "Irlanda", "irlandês", "Islândia", "islandês", "Itália", "italiano",
    "Jamaica", "jamaicano", "Japão", "japonês",
    "Luxemburgo", "luxemburguês",
    "Marrocos", "marroquino", "México", "mexicano", "Moçambique", "moçambicano",
    "Noruega", "norueguês", "Nigéria", "nigeriano", "Nova Zelândia", "neozelandês",
    "País de Gales", "galês", "Países Baixos", "Peru", "peruano", "Paquistão", "paquistanês", "Filipinas", "filipino", "Polónia", "polaco", "Portugal", "português",
    "Quénia", "queniano",
    "Reino Unido", "britânico", "Roménia", "romeno", "Rússia", "russo",
    "São Tomé e Príncipe", "são-tomense", "Senegal", "senegalês", "Suécia", "sueco", "Suíça", "suíço",
    "Tailândia", "tailandês", "Timor-Leste", "timorense", "Tunísia", "tunisino", "Turquia", "turco",
    "Ucrânia", "ucraniano", "Uruguai", "uruguaio",
    "Venezuela", "venezuelano", "Vietname", "vietnamita",
    "Zimbabué", "zimbabueano",
  ],
  lugar: [
    "aeroporto", "aldeia", "adega", "areia", "arco-íris", "árvore", "autoestrada", "avenida",
    "banco", "bar", "bairro", "biblioteca", "bosque",
    "café", "campo", "cabana", "casa", "casa de banho", "castelo", "centro comercial", "céu", "cidade", "cinema", "correios", "costa", "cozinha",
    "deserto", "discoteca",
    "escola", "escritório", "esplanada", "esquadra", "estação", "estádio", "estrada", "estrela",
    "farmácia", "fábrica", "flor", "floresta", "fonte",
    "garagem", "ginásio", "gruta",
    "horta", "hospital", "hotel",
    "igreja", "ilha",
    "jardim",
    "lago", "lagoa", "livraria", "loja", "lua",
    "mar", "mercado", "mercearia", "miradouro", "montanha", "museu",
    "neve", "nuvem",
    "oceano", "oficina", "onda",
    "padaria", "parque", "pastelaria", "piscina", "pinhal", "planeta", "ponte", "porto", "praça", "praia", "prédio",
    "quarto", "quinta", "quiosque",
    "restaurante", "rio", "rotunda", "rua",
    "sala", "sala de aula", "selva", "serra", "sol", "supermercado",
    "talho", "tasca", "teatro", "terra",
    "universidade",
    "vale", "vila", "vinha", "vulcão",
    "zoo",
  ],
};
