/**
 * Companion data for the Stop! reference words (./reference.ts): an English gloss for every word,
 * plus the subset that is too advanced or obscure to SUGGEST to A1 beginners. Kept separate so
 * reference.ts stays a plain word list.
 */

/** English gloss for every REFERENCE word (key = the exact REFERENCE string). */
export const GLOSS: Record<string, string> = {
  // ── comida ──
  "açúcar": "sugar", "água": "water", "alface": "lettuce", "alho": "garlic", "almôndega": "meatball",
  "ameixa": "plum", "amêndoa": "almond", "amendoim": "peanut", "ananás": "pineapple", "arroz": "rice",
  "atum": "tuna", "azeite": "olive oil", "azeitona": "olive",
  "bacalhau": "salt cod", "banana": "banana", "batata": "potato", "batata frita": "fries", "bica": "espresso",
  "bife": "steak", "bifana": "pork sandwich", "bolacha": "biscuit", "bolo": "cake", "bolo-rei": "king cake",
  "broa": "corn bread", "brócolos": "broccoli",
  "café": "coffee; café", "caldo verde": "kale soup", "camarão": "shrimp", "caracóis": "snails", "carne": "meat",
  "caril": "curry", "castanha": "chestnut", "cebola": "onion", "cenoura": "carrot", "cereja": "cherry",
  "cerveja": "beer", "chá": "tea", "chocolate": "chocolate", "chouriço": "chorizo", "cogumelo": "mushroom",
  "compota": "jam", "couve": "cabbage", "cozido": "meat stew", "croissant": "croissant", "croquete": "croquette",
  "damasco": "apricot", "doce": "sweet",
  "empada": "savoury pie",
  "ervilha": "pea", "esparguete": "spaghetti", "espinafre": "spinach",
  "farinha": "flour", "feijão": "beans", "fiambre": "ham", "figo": "fig", "framboesa": "raspberry",
  "francesinha": "Porto sandwich", "frango": "chicken", "fruta": "fruit",
  "galão": "milky coffee", "gelado": "ice cream", "gelatina": "jelly", "gaspacho": "gazpacho", "grão": "chickpeas",
  "hambúrguer": "burger", "hortelã": "mint",
  "iogurte": "yogurt",
  "laranja": "orange", "lagosta": "lobster", "leite": "milk", "limão": "lemon", "limonada": "lemonade",
  "linguado": "sole (fish)", "lula": "squid",
  "maçã": "apple", "manga": "mango", "manteiga": "butter", "marmelada": "quince paste", "massa": "pasta",
  "mel": "honey", "melancia": "watermelon", "melão": "melon", "morango": "strawberry", "mostarda": "mustard",
  "nabo": "turnip", "natas": "cream", "noz": "walnut",
  "omelete": "omelette", "ovo": "egg",
  "pão": "bread", "pastel de nata": "custard tart", "patanisca": "cod fritter", "peixe": "fish",
  "pepino": "cucumber", "pequeno-almoço": "breakfast", "pera": "pear", "pêssego": "peach",
  "pimento": "bell pepper", "pizza": "pizza", "pipoca": "popcorn", "polvo": "octopus", "presunto": "cured ham",
  "pudim": "flan",
  "queijada": "cheese tart", "queijo": "cheese",
  "rabanada": "French toast", "requeijão": "curd cheese", "rissol": "fried pastry",
  "sal": "salt", "salada": "salad", "salmão": "salmon", "salsicha": "sausage", "sandes": "sandwich",
  "sardinha": "sardine", "sopa": "soup", "sumo": "juice",
  "tangerina": "tangerine", "tomate": "tomato", "torrada": "toast", "tosta mista": "ham-cheese toastie",
  "tremoço": "lupin bean",
  "uva": "grape",
  "vinagre": "vinegar", "vinho": "wine", "vitela": "veal",

  // ── animal ── (lagosta, lula, peixe, polvo, salmão, sardinha are under comida)
  "abelha": "bee", "águia": "eagle", "alforreca": "jellyfish", "andorinha": "swallow", "aranha": "spider",
  "avestruz": "ostrich",
  "baleia": "whale", "bode": "billy goat", "borboleta": "butterfly", "búfalo": "buffalo", "burro": "donkey",
  "cabra": "goat", "camelo": "camel", "canguru": "kangaroo", "canário": "canary", "cão": "dog", "caracol": "snail",
  "caranguejo": "crab", "carneiro": "ram", "cavalo": "horse", "cegonha": "stork", "cisne": "swan",
  "cobra": "snake", "coelho": "rabbit", "coruja": "owl", "crocodilo": "crocodile",
  "dinossauro": "dinosaur",
  "elefante": "elephant", "esquilo": "squirrel", "enguia": "eel", "estrela-do-mar": "starfish",
  "falcão": "falcon", "flamingo": "flamingo", "foca": "seal", "formiga": "ant",
  "gaivota": "seagull", "galinha": "hen", "galo": "rooster", "gato": "cat", "gafanhoto": "grasshopper",
  "gazela": "gazelle", "girafa": "giraffe", "golfinho": "dolphin", "gorila": "gorilla", "grilo": "cricket",
  "hamster": "hamster", "hipopótamo": "hippo",
  "iguana": "iguana",
  "jacaré": "alligator", "javali": "wild boar", "joaninha": "ladybird",
  "lagarto": "lizard", "leão": "lion", "leopardo": "leopard", "lesma": "slug", "lince": "lynx", "lobo": "wolf",
  "lontra": "otter",
  "macaco": "monkey", "minhoca": "earthworm", "mocho": "little owl", "morcego": "bat", "mosca": "fly",
  "mosquito": "mosquito",
  "orca": "orca", "ouriço": "hedgehog", "ovelha": "sheep",
  "panda": "panda", "papagaio": "parrot", "periquito": "budgie", "pássaro": "bird", "pato": "duck",
  "pinguim": "penguin", "pombo": "pigeon", "pónei": "pony", "porco": "pig", "pulga": "flea", "peru": "turkey",
  "rã": "frog", "raposa": "fox", "rato": "mouse", "rinoceronte": "rhino",
  "sapo": "toad", "serpente": "serpent",
  "tartaruga": "turtle", "tigre": "tiger", "toupeira": "mole", "touro": "bull", "tubarão": "shark",
  "urso": "bear",
  "vaca": "cow", "veado": "deer", "vespa": "wasp",
  "zebra": "zebra",

  // ── coisa ── (banco is under lugar)
  "almofada": "cushion", "anel": "ring", "armário": "cupboard", "aspirador": "vacuum cleaner", "autocarro": "bus",
  "avião": "plane",
  "balão": "balloon", "balde": "bucket", "barco": "boat", "bicicleta": "bicycle", "bola": "ball", "boné": "cap",
  "borracha": "eraser", "botão": "button", "brinco": "earring",
  "cadeira": "chair", "caderno": "notebook", "caixa": "box", "cama": "bed", "camisola": "sweater", "caneca": "mug",
  "caneta": "pen", "carro": "car", "cachecol": "scarf", "calças": "trousers", "carteira": "wallet",
  "casaco": "coat", "chapéu": "hat", "chave": "key", "chávena": "cup", "chuveiro": "shower", "cinto": "belt",
  "colher": "spoon", "comboio": "train", "computador": "computer", "copo": "glass", "cortina": "curtain",
  "despertador": "alarm clock", "dinheiro": "money",
  "elétrico": "tram", "envelope": "envelope", "escova": "brush", "escada": "stairs", "espelho": "mirror",
  "estojo": "pencil case",
  "faca": "knife", "fogão": "stove", "fotografia": "photo", "frigideira": "frying pan", "frigorífico": "fridge",
  "garfo": "fork", "garrafa": "bottle", "gaveta": "drawer", "guarda-chuva": "umbrella", "guitarra": "guitar",
  "helicóptero": "helicopter",
  "isqueiro": "lighter",
  "janela": "window", "jogo": "game", "jornal": "newspaper",
  "lâmpada": "light bulb", "lápis": "pencil", "livro": "book", "luva": "glove",
  "mala": "bag; suitcase", "máquina de lavar": "washing machine", "meia": "sock", "mesa": "table",
  "micro-ondas": "microwave", "mochila": "backpack", "moeda": "coin", "mota": "motorbike",
  "navio": "ship",
  "óculos": "glasses",
  "panela": "saucepan", "papel": "paper", "pente": "comb", "piano": "piano", "porta": "door", "postal": "postcard",
  "prato": "plate", "presente": "present", "pulseira": "bracelet",
  "quadro": "painting; board",
  "rádio": "radio", "régua": "ruler", "relógio": "watch; clock",
  "sabonete": "soap", "saco": "bag", "sanita": "toilet", "sapatilha": "trainer", "sapato": "shoe",
  "secador": "hairdryer", "selo": "stamp", "sofá": "sofa",
  "tacho": "cooking pot", "tapete": "rug", "telemóvel": "mobile phone", "televisão": "television",
  "tesoura": "scissors", "toalha": "towel", "torradeira": "toaster", "trotinete": "scooter",
  "urso de peluche": "teddy bear",
  "vassoura": "broom", "vela": "candle", "ventoinha": "fan", "vestido": "dress",
  "xadrez": "chess",

  // ── profissao ──
  "advogado": "lawyer", "agricultor": "farmer", "apicultor": "beekeeper", "arquiteto": "architect",
  "artista": "artist", "assistente de bordo": "flight attendant", "astronauta": "astronaut", "ator": "actor",
  "bailarino": "dancer", "bancário": "bank clerk", "barbeiro": "barber", "baterista": "drummer",
  "bibliotecário": "librarian", "biólogo": "biologist", "bombeiro": "firefighter",
  "cabeleireiro": "hairdresser", "calceteiro": "cobblestone paver", "canalizador": "plumber", "cantor": "singer",
  "carpinteiro": "carpenter", "carteiro": "postman", "cientista": "scientist", "cirurgião": "surgeon",
  "condutor": "driver", "contabilista": "accountant", "cozinheiro": "cook", "costureiro": "dressmaker",
  "dentista": "dentist", "diplomata": "diplomat",
  "economista": "economist", "eletricista": "electrician", "empregado de balcão": "counter assistant",
  "empregado de limpeza": "cleaner", "empregado de mesa": "waiter", "empresário": "business owner",
  "enfermeiro": "nurse", "engenheiro": "engineer", "escritor": "writer", "estilista": "fashion designer",
  "estudante": "student", "explicador": "tutor",
  "fadista": "fado singer", "farmacêutico": "pharmacist", "fisioterapeuta": "physiotherapist",
  "florista": "florist", "fotógrafo": "photographer", "futebolista": "footballer",
  "gestor": "manager", "guia": "guide", "guarda-florestal": "forest ranger", "guitarrista": "guitarist",
  "historiador": "historian",
  "ilustrador": "illustrator", "informático": "IT worker", "intérprete": "interpreter",
  "jardineiro": "gardener", "jogador": "player", "jornalista": "journalist", "juiz": "judge",
  "lojista": "shopkeeper",
  "maquinista": "train driver", "marinheiro": "sailor", "matemático": "mathematician", "mecânico": "mechanic",
  "médico": "doctor", "mergulhador": "diver", "merceeiro": "grocer", "militar": "serviceman", "modelo": "model",
  "motorista": "driver", "músico": "musician",
  "nadador-salvador": "lifeguard", "nutricionista": "nutritionist",
  "operador de caixa": "cashier", "ourives": "goldsmith",
  "padeiro": "baker", "pasteleiro": "pastry chef", "pastor": "shepherd", "pedreiro": "bricklayer",
  "peixeiro": "fishmonger", "pescador": "fisherman", "pianista": "pianist", "piloto": "pilot", "pintor": "painter",
  "polícia": "police officer", "político": "politician", "porteiro": "doorman", "professor": "teacher",
  "programador": "programmer", "psicólogo": "psychologist",
  "químico": "chemist",
  "realizador": "film director", "rececionista": "receptionist",
  "sapateiro": "shoemaker", "secretário": "secretary", "segurança": "security guard", "soldado": "soldier",
  "surfista": "surfer",
  "talhante": "butcher", "taxista": "taxi driver", "técnico": "technician", "tradutor": "translator",
  "treinador": "coach",
  "vendedor": "salesperson", "veterinário": "vet", "vigilante": "watchman", "violinista": "violinist",

  // ── pais ──
  "Alemanha": "Germany", "alemão": "German", "Angola": "Angola", "angolano": "Angolan",
  "Argentina": "Argentina", "argentino": "Argentinian", "Austrália": "Australia", "australiano": "Australian",
  "Áustria": "Austria", "austríaco": "Austrian",
  "Bélgica": "Belgium", "belga": "Belgian", "Brasil": "Brazil", "brasileiro": "Brazilian",
  "Bulgária": "Bulgaria", "búlgaro": "Bulgarian",
  "Cabo Verde": "Cape Verde", "cabo-verdiano": "Cape Verdean", "Canadá": "Canada", "canadiano": "Canadian",
  "Chile": "Chile", "chileno": "Chilean", "China": "China", "chinês": "Chinese", "Colômbia": "Colombia",
  "colombiano": "Colombian", "Coreia do Sul": "South Korea", "coreano": "Korean", "Croácia": "Croatia",
  "croata": "Croatian", "Cuba": "Cuba", "cubano": "Cuban",
  "Dinamarca": "Denmark", "dinamarquês": "Danish",
  "Egito": "Egypt", "egípcio": "Egyptian", "Escócia": "Scotland", "escocês": "Scottish", "Espanha": "Spain",
  "espanhol": "Spanish", "Estados Unidos": "United States", "americano": "American",
  "norte-americano": "American",
  "Finlândia": "Finland", "finlandês": "Finnish", "França": "France", "francês": "French",
  "Grécia": "Greece", "grego": "Greek", "Guiné-Bissau": "Guinea-Bissau", "guineense": "Guinean",
  "Holanda": "Holland", "holandês": "Dutch", "Hungria": "Hungary", "húngaro": "Hungarian",
  "Índia": "India", "indiano": "Indian", "Inglaterra": "England", "inglês": "English", "Irão": "Iran",
  "iraniano": "Iranian", "Irlanda": "Ireland", "irlandês": "Irish", "Islândia": "Iceland",
  "islandês": "Icelandic", "Itália": "Italy", "italiano": "Italian",
  "Jamaica": "Jamaica", "jamaicano": "Jamaican", "Japão": "Japan", "japonês": "Japanese",
  "Luxemburgo": "Luxembourg", "luxemburguês": "Luxembourgish",
  "Marrocos": "Morocco", "marroquino": "Moroccan", "México": "Mexico", "mexicano": "Mexican",
  "Moçambique": "Mozambique", "moçambicano": "Mozambican",
  "Noruega": "Norway", "norueguês": "Norwegian", "Nigéria": "Nigeria", "nigeriano": "Nigerian",
  "Nova Zelândia": "New Zealand", "neozelandês": "New Zealander",
  "País de Gales": "Wales", "galês": "Welsh", "Países Baixos": "Netherlands", "Peru": "Peru",
  "peruano": "Peruvian", "Paquistão": "Pakistan", "paquistanês": "Pakistani", "Filipinas": "Philippines",
  "filipino": "Filipino", "Polónia": "Poland", "polaco": "Polish", "Portugal": "Portugal",
  "português": "Portuguese",
  "Quénia": "Kenya", "queniano": "Kenyan",
  "Reino Unido": "United Kingdom", "britânico": "British", "Roménia": "Romania", "romeno": "Romanian",
  "Rússia": "Russia", "russo": "Russian",
  "São Tomé e Príncipe": "São Tomé and Príncipe", "são-tomense": "São Tomean", "Senegal": "Senegal",
  "senegalês": "Senegalese", "Suécia": "Sweden", "sueco": "Swedish", "Suíça": "Switzerland", "suíço": "Swiss",
  "Tailândia": "Thailand", "tailandês": "Thai", "Timor-Leste": "East Timor", "timorense": "Timorese",
  "Tunísia": "Tunisia", "tunisino": "Tunisian", "Turquia": "Turkey", "turco": "Turkish",
  "Ucrânia": "Ukraine", "ucraniano": "Ukrainian", "Uruguai": "Uruguay", "uruguaio": "Uruguayan",
  "Venezuela": "Venezuela", "venezuelano": "Venezuelan", "Vietname": "Vietnam", "vietnamita": "Vietnamese",
  "Zimbabué": "Zimbabwe", "zimbabueano": "Zimbabwean",

  // ── lugar ── (café is under comida)
  "aeroporto": "airport", "aldeia": "village", "adega": "wine cellar", "areia": "sand", "arco-íris": "rainbow",
  "árvore": "tree", "autoestrada": "motorway", "avenida": "avenue",
  "banco": "bank; bench", "bar": "bar", "bairro": "neighbourhood", "biblioteca": "library", "bosque": "woods",
  "campo": "countryside", "cabana": "hut", "casa": "house", "casa de banho": "bathroom", "castelo": "castle",
  "centro comercial": "shopping centre", "céu": "sky", "cidade": "city", "cinema": "cinema",
  "correios": "post office", "costa": "coast", "cozinha": "kitchen",
  "deserto": "desert", "discoteca": "nightclub",
  "escola": "school", "escritório": "office", "esplanada": "café terrace", "esquadra": "police station",
  "estação": "station", "estádio": "stadium", "estrada": "road", "estrela": "star",
  "farmácia": "pharmacy", "fábrica": "factory", "flor": "flower", "floresta": "forest", "fonte": "fountain",
  "garagem": "garage", "ginásio": "gym", "gruta": "cave",
  "horta": "vegetable garden", "hospital": "hospital", "hotel": "hotel",
  "igreja": "church", "ilha": "island",
  "jardim": "garden",
  "lago": "lake", "lagoa": "lagoon", "livraria": "bookshop", "loja": "shop", "lua": "moon",
  "mar": "sea", "mercado": "market", "mercearia": "grocery shop", "miradouro": "viewpoint",
  "montanha": "mountain", "museu": "museum",
  "neve": "snow", "nuvem": "cloud",
  "oceano": "ocean", "oficina": "workshop", "onda": "wave",
  "padaria": "bakery", "parque": "park", "pastelaria": "pastry shop", "piscina": "swimming pool",
  "pinhal": "pine forest", "planeta": "planet", "ponte": "bridge", "porto": "port", "praça": "square",
  "praia": "beach", "prédio": "building",
  "quarto": "bedroom", "quinta": "farm", "quiosque": "kiosk",
  "restaurante": "restaurant", "rio": "river", "rotunda": "roundabout", "rua": "street",
  "sala": "living room", "sala de aula": "classroom", "selva": "jungle", "serra": "mountain range", "sol": "sun",
  "supermercado": "supermarket",
  "talho": "butcher's", "tasca": "tavern", "teatro": "theatre", "terra": "earth; land",
  "universidade": "university",
  "vale": "valley", "vila": "town", "vinha": "vineyard", "vulcão": "volcano",
  "zoo": "zoo",
};

/** REFERENCE words that are too advanced (above A2) or too obscure/regional to SUGGEST to A1 beginners. They still count as known words; they're just never shown as suggestions. */
export const NOT_FOR_SUGGESTIONS: ReadonlySet<string> = new Set([
  // comida
  "empada", "gaspacho", "linguado", "nabo", "patanisca", "queijada", "rabanada", "requeijão", "rissol",
  // animal
  "alforreca", "bode", "cegonha", "enguia", "gafanhoto", "javali", "lince", "lontra", "mocho", "toupeira",
  // coisa
  "tacho",
  // profissao
  "apicultor", "calceteiro", "cirurgião", "costureiro", "diplomata", "economista", "farmacêutico",
  "fisioterapeuta", "guarda-florestal", "historiador", "merceeiro", "nutricionista", "ourives", "vigilante",
  // pais
  "Filipinas", "filipino", "neozelandês", "Senegal", "senegalês", "Tunísia", "tunisino", "uruguaio",
  "Zimbabué", "zimbabueano",
  // lugar
  "adega", "pinhal", "vinha",
]);
