/**
 * Na Mesma Onda "thing" clues (Wavelength spirit): for each spectrum, everyday things spread over
 * the whole dial, from obvious extremes through middle-ish things to a few debatable ones that are
 * fun to argue about ("o mar é frio?" — in Portugal, the Atlantic says yes). Pure data.
 */

/** A thing the psychic can use as a clue, with where most people would put it (0 = left pole, 100 = right pole). The position is only a hint for bots/tests; scoring never uses it. */
export interface ThingClue {
  noun: string;
  at: number;
}

/** Keyed "<leftSlug>|<rightSlug>" exactly as spectra() orders them. `noun` is a slug of vocab.noun.<slug>. */
export const THINGS: Record<string, ThingClue[]> = {
  "frio|quente": [
    { noun: "gelo", at: 3 },
    { noun: "gelado", at: 6 },
    { noun: "neve", at: 8 },
    { noun: "cerveja", at: 20 },
    { noun: "mar", at: 25 }, // the Atlantic in Portugal: debatable
    { noun: "sumo", at: 28 },
    { noun: "agua", at: 38 },
    { noun: "salada", at: 42 },
    { noun: "leite", at: 45 },
    { noun: "pao", at: 55 },
    { noun: "chuveiro", at: 70 }, // depends who showers first
    { noun: "sopa", at: 82 },
    { noun: "cha", at: 85 },
    { noun: "cafe", at: 88 },
    { noun: "sol", at: 93 },
    { noun: "fogo", at: 98 },
  ],
  "grande|pequeno": [
    { noun: "montanha", at: 3 },
    { noun: "elefante", at: 8 },
    { noun: "aviao", at: 10 },
    { noun: "comboio", at: 14 },
    { noun: "estrela", at: 20 }, // enormous, but it looks tiny
    { noun: "cavalo", at: 28 },
    { noun: "sofa", at: 36 },
    { noun: "televisao", at: 42 },
    { noun: "cao", at: 48 }, // a Serra da Estrela or a chihuahua?
    { noun: "gato", at: 62 },
    { noun: "telemovel", at: 70 },
    { noun: "maca", at: 76 },
    { noun: "ovo", at: 82 },
    { noun: "rato", at: 85 },
    { noun: "chave", at: 88 },
    { noun: "abelha", at: 95 },
  ],
  "barato|caro": [
    { noun: "sal", at: 3 },
    { noun: "agua", at: 5 },
    { noun: "pao", at: 6 },
    { noun: "cafe", at: 10 }, // a bica in Portugal
    { noun: "batata", at: 12 },
    { noun: "cerveja", at: 20 },
    { noun: "gelado", at: 28 },
    { noun: "pizza", at: 38 },
    { noun: "livro", at: 40 },
    { noun: "vinho", at: 48 }, // from €2 to €200
    { noun: "sapatilhas", at: 55 },
    { noun: "guitarra", at: 62 },
    { noun: "relogio", at: 70 },
    { noun: "telemovel", at: 78 },
    { noun: "carro", at: 92 },
    { noun: "casa", at: 98 },
  ],
  "feliz|triste": [
    { noun: "presente", at: 5 },
    { noun: "bolo", at: 7 },
    { noun: "arco_iris", at: 10 },
    { noun: "praia", at: 14 },
    { noun: "cao", at: 20 },
    { noun: "flor", at: 22 },
    { noun: "gato", at: 28 },
    { noun: "dinheiro", at: 35 }, // does it buy happiness?
    { noun: "escola", at: 45 },
    { noun: "lua", at: 50 },
    { noun: "jornal", at: 60 }, // the news…
    { noun: "nuvem", at: 64 },
    { noun: "guarda_chuva", at: 70 },
    { noun: "chuva", at: 76 },
    { noun: "cebola", at: 82 }, // it makes you cry
    { noun: "hospital", at: 86 },
  ],
  "dificil|facil": [
    { noun: "aviao", at: 4 }, // flying one
    { noun: "barco", at: 15 },
    { noun: "guitarra", at: 18 },
    { noun: "croissant", at: 22 }, // making one at home
    { noun: "cavalo", at: 25 },
    { noun: "pao", at: 32 },
    { noun: "mota", at: 38 },
    { noun: "carro", at: 42 }, // parking in Lisbon…
    { noun: "computador", at: 48 },
    { noun: "gato", at: 55 },
    { noun: "livro", at: 62 },
    { noun: "bicicleta", at: 72 }, // once you know how
    { noun: "telemovel", at: 76 },
    { noun: "ovo", at: 85 },
    { noun: "bola", at: 88 },
    { noun: "televisao", at: 96 },
  ],
  "lento|rapido": [
    { noun: "caracol", at: 2 },
    { noun: "vaca", at: 14 },
    { noun: "elefante", at: 26 }, // they can run!
    { noun: "eletrico", at: 28 },
    { noun: "autocarro", at: 36 },
    { noun: "barco", at: 40 },
    { noun: "trotinete", at: 44 },
    { noun: "bicicleta", at: 48 },
    { noun: "metro", at: 58 },
    { noun: "gato", at: 64 },
    { noun: "comboio", at: 70 }, // Alfa Pendular or the regional?
    { noun: "passaro", at: 72 },
    { noun: "cavalo", at: 78 },
    { noun: "carro", at: 80 },
    { noun: "mota", at: 84 },
    { noun: "aviao", at: 96 },
  ],
  "bom|mau": [
    { noun: "chocolate", at: 5 },
    { noun: "bolo", at: 7 },
    { noun: "gelado", at: 10 },
    { noun: "praia", at: 14 },
    { noun: "pizza", at: 16 },
    { noun: "cafe", at: 20 },
    { noun: "sopa", at: 26 },
    { noun: "salada", at: 38 }, // good for you, but…
    { noun: "cerveja", at: 45 },
    { noun: "hamburguer", at: 48 },
    { noun: "abelha", at: 55 }, // honey or a sting?
    { noun: "cebola", at: 58 },
    { noun: "chuva", at: 62 },
    { noun: "fogo", at: 74 },
    { noun: "rato", at: 80 },
    { noun: "tubarao", at: 86 },
  ],
  "novo|velho": [
    { noun: "presente", at: 4 },
    { noun: "trotinete", at: 8 },
    { noun: "telemovel", at: 10 },
    { noun: "computador", at: 18 },
    { noun: "sapatilhas", at: 22 },
    { noun: "televisao", at: 38 },
    { noun: "aviao", at: 42 },
    { noun: "carro", at: 45 },
    { noun: "bicicleta", at: 52 },
    { noun: "comboio", at: 58 },
    { noun: "livro", at: 62 },
    { noun: "vinho", at: 70 }, // old wine is good wine
    { noun: "eletrico", at: 76 }, // Lisbon's trams
    { noun: "igreja", at: 85 },
    { noun: "castelo", at: 92 },
    { noun: "montanha", at: 98 },
  ],
  "bonito|feio": [
    { noun: "arco_iris", at: 3 },
    { noun: "flor", at: 5 },
    { noun: "praia", at: 8 },
    { noun: "mar", at: 12 },
    { noun: "estrela", at: 14 },
    { noun: "castelo", at: 20 },
    { noun: "cavalo", at: 26 },
    { noun: "nuvem", at: 36 },
    { noun: "cao", at: 40 },
    { noun: "chapeu", at: 48 }, // depends on the hat
    { noun: "vaca", at: 52 },
    { noun: "guarda_chuva", at: 58 },
    { noun: "caracol", at: 68 },
    { noun: "porco", at: 72 }, // some people love pigs
    { noun: "rato", at: 78 },
    { noun: "sanita", at: 86 },
  ],
  "barulhento|calmo": [
    { noun: "aviao", at: 3 },
    { noun: "mota", at: 8 },
    { noun: "aeroporto", at: 12 },
    { noun: "guitarra", at: 20 },
    { noun: "cao", at: 24 },
    { noun: "escola", at: 30 },
    { noun: "carro", at: 36 },
    { noun: "galinha", at: 42 },
    { noun: "praia", at: 52 }, // August or October?
    { noun: "mar", at: 58 },
    { noun: "cinema", at: 62 },
    { noun: "gato", at: 72 },
    { noun: "arvore", at: 78 },
    { noun: "museu", at: 82 },
    { noun: "livro", at: 90 },
    { noun: "peixe", at: 94 },
  ],
  "leve|pesado": [
    { noun: "balao", at: 2 },
    { noun: "meia", at: 5 },
    { noun: "lapis", at: 7 },
    { noun: "bola", at: 20 },
    { noun: "telemovel", at: 24 },
    { noun: "guitarra", at: 36 },
    { noun: "livro", at: 38 },
    { noun: "gato", at: 44 },
    { noun: "mochila", at: 52 }, // a school bag on a Monday…
    { noun: "bicicleta", at: 58 },
    { noun: "melancia", at: 64 },
    { noun: "mala", at: 68 },
    { noun: "sofa", at: 78 },
    { noun: "cavalo", at: 85 },
    { noun: "carro", at: 90 },
    { noun: "elefante", at: 96 },
  ],
  "limpo|sujo": [
    { noun: "chuveiro", at: 3 },
    { noun: "neve", at: 8 },
    { noun: "hospital", at: 10 },
    { noun: "agua", at: 15 },
    { noun: "gato", at: 24 }, // cats wash all day
    { noun: "cama", at: 28 },
    { noun: "praia", at: 38 },
    { noun: "mao", at: 50 },
    { noun: "carro", at: 55 },
    { noun: "metro", at: 60 },
    { noun: "cao", at: 64 },
    { noun: "sapatilhas", at: 70 },
    { noun: "telemovel", at: 72 }, // dirtier than you think
    { noun: "meia", at: 78 },
    { noun: "dinheiro", at: 80 },
    { noun: "porco", at: 92 },
  ],
  // Unit 2: describing people
  "alto|baixo": [
    { noun: "montanha", at: 2 },
    { noun: "arvore", at: 8 },
    { noun: "castelo", at: 12 },
    { noun: "igreja", at: 15 },
    { noun: "elefante", at: 22 },
    { noun: "autocarro", at: 30 },
    { noun: "cavalo", at: 38 },
    { noun: "pai", at: 42 }, // depends whose father
    { noun: "porta", at: 45 },
    { noun: "mae", at: 52 },
    { noun: "cadeira", at: 70 },
    { noun: "cao", at: 74 },
    { noun: "gato", at: 82 },
    { noun: "neto", at: 86 },
    { noun: "rato", at: 93 },
    { noun: "caracol", at: 97 },
  ],
  "antipatico|simpatico": [
    { noun: "tubarao", at: 5 },
    { noun: "leao", at: 15 },
    { noun: "abelha", at: 25 },
    { noun: "rato", at: 40 },
    { noun: "galinha", at: 45 },
    { noun: "gato", at: 50 }, // cat people vs dog people
    { noun: "colega", at: 58 },
    { noun: "tio", at: 68 },
    { noun: "cavalo", at: 72 },
    { noun: "cao", at: 90 },
    { noun: "avo_f", at: 93 },
    { noun: "amiga", at: 96 },
  ],
  "preguicoso|trabalhador": [
    { noun: "gato", at: 5 },
    { noun: "sofa", at: 8 },
    { noun: "caracol", at: 15 },
    { noun: "leao", at: 22 },
    { noun: "porco", at: 28 },
    { noun: "tio", at: 42 },
    { noun: "vaca", at: 50 },
    { noun: "colega", at: 55 }, // depends on the colleague
    { noun: "cao", at: 60 },
    { noun: "cavalo", at: 82 },
    { noun: "mae", at: 90 },
    { noun: "abelha", at: 97 },
  ],
  "impaciente|paciente": [
    { noun: "neto", at: 6 },
    { noun: "filho", at: 12 },
    { noun: "cao", at: 22 }, // at dinner time
    { noun: "galinha", at: 35 },
    { noun: "gato", at: 45 },
    { noun: "colega", at: 50 },
    { noun: "pai", at: 58 },
    { noun: "vaca", at: 75 },
    { noun: "avo_f", at: 88 },
    { noun: "caracol", at: 92 },
    { noun: "arvore", at: 96 },
    { noun: "montanha", at: 99 },
  ],
  // Units 5–6: colours, weather, health
  "branco|preto": [
    { noun: "leite", at: 3 },
    { noun: "neve", at: 4 },
    { noun: "acucar", at: 6 },
    { noun: "sal", at: 8 },
    { noun: "nuvem", at: 10 },
    { noun: "arroz", at: 12 },
    { noun: "ovo", at: 15 },
    { noun: "lua", at: 25 },
    { noun: "gelado", at: 40 }, // depends on the flavour
    { noun: "gato", at: 50 }, // depends on the cat
    { noun: "cao", at: 55 },
    { noun: "carro", at: 55 },
    { noun: "guitarra", at: 60 },
    { noun: "computador", at: 70 },
    { noun: "mala", at: 75 },
    { noun: "telemovel", at: 80 },
    { noun: "chocolate", at: 85 },
    { noun: "cafe", at: 92 },
  ],
  "molhado|seco": [
    { noun: "mar", at: 2 },
    { noun: "chuva", at: 3 },
    { noun: "agua", at: 4 },
    { noun: "chuveiro", at: 8 },
    { noun: "sopa", at: 12 },
    { noun: "peixe", at: 15 },
    { noun: "neve", at: 20 },
    { noun: "gelo", at: 25 },
    { noun: "nuvem", at: 30 },
    { noun: "flor", at: 45 },
    { noun: "arvore", at: 50 },
    { noun: "praia", at: 55 }, // depends where you lie down
    { noun: "pao", at: 85 },
    { noun: "livro", at: 88 },
    { noun: "bolacha", at: 92 },
    { noun: "acucar", at: 94 },
    { noun: "sal", at: 95 },
    { noun: "sol", at: 97 },
    { noun: "fogo", at: 98 },
  ],
  "doente|saudavel": [
    { noun: "febre", at: 3 },
    { noun: "gripe", at: 5 },
    { noun: "constipacao", at: 8 },
    { noun: "tosse", at: 10 },
    { noun: "acucar", at: 15 },
    { noun: "hamburguer", at: 18 },
    { noun: "cerveja", at: 20 },
    { noun: "bolo", at: 22 },
    { noun: "chocolate", at: 25 },
    { noun: "vinho", at: 35 },
    { noun: "cafe", at: 40 }, // the eternal debate
    { noun: "queijo", at: 50 },
    { noun: "pao", at: 55 },
    { noun: "ovo", at: 60 },
    { noun: "leite", at: 62 },
    { noun: "peixe", at: 78 },
    { noun: "sopa", at: 82 },
    { noun: "salada", at: 90 },
    { noun: "maca", at: 92 },
    { noun: "agua", at: 95 },
  ],
};
